### ISSUE TITLE
Failed tx shows as complete

### ISSUE THREAD

**Issue by phiferd** [Musicoin/orbiter#12]
http://orbiter.musicoin.org/tx/0xb8849a00645367b087ff721a9e09a92ccc8dd3a1109c179cb8bcc0410e9fe94d

I believe this transaction failed due to an exception.  However, in orbiter is appears to have succeeded.  I suspect that an additional check is needed to see if the gasUsed == gas.  Maybe this can be addressed when #4 is addressed, since both require gasUsed information (which is only in the receipt).

(and don't get me started on how stupid it is to check if gasUsed==gas to see if there is a failure, or how it is actually possible that gasUsed == gas when everything went fine)

**Comment by immartian** [comment]
Will investigate soon.

**Comment by immartian** [comment]
Some clear evidences found in the spotted tx:

Envelope tx:
{"action":{"callType":"call","from":"0xe5233d15f4993c83f066575accde2ce10e369188","gas":"**0xe04c8**","input":"0x93e84cd9","to":"0xbd6a01b9c28d1ebcf13f63d8b0814418211fbf9d","value":"0xde0b6b3a7640000"},"blockHash":"0x2179e324a56413857636a6f034baaf2e8c4d3427b78a2d6288583bbd5c3cac34","blockNumber":141818,**"error":"Out of gas"**,"subtraces":2,"traceAddress":[],"transactionHash":"0xb8849a00645367b087ff721a9e09a92ccc8dd3a1109c179cb8bcc0410e9fe94d","transactionPosition":8,"type":"call"},

Internal Tx1:
{"action":{"callType":"call","from":"0xbd6a01b9c28d1ebcf13f63d8b0814418211fbf9d","gas":"0xd724f","input":"0x","to":"0x4c54039e4480031f69226e2ec19454b239230870","value":"0x4a03ce68d215555"},"blockHash":"0x2179e324a56413857636a6f034baaf2e8c4d3427b78a2d6288583bbd5c3cac34","blockNumber":141818,"result":{"gasUsed":"0x33","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xb8849a00645367b087ff721a9e09a92ccc8dd3a1109c179cb8bcc0410e9fe94d","transactionPosition":8,"type":"call"},

Internal Tx2: 
{"action":{"callType":"call","from":"0xbd6a01b9c28d1ebcf13f63d8b0814418211fbf9d","gas":"0xd0e79","input":"0x","to":"0xc372b9907c1f22ce6d4deffc4e2c1deffb076a82","value":"0x4a03ce68d215555"},"blockHash":"0x2179e324a56413857636a6f034baaf2e8c4d3427b78a2d6288583bbd5c3cac34","blockNumber":141818,**"error":"Bad jump destination"**,"subtraces":0,"traceAddress":[1],"transactionHash":"0xb8849a00645367b087ff721a9e09a92ccc8dd3a1109c179cb8bcc0410e9fe94d","transactionPosition":8,"type":"call"}]

Need to add a field in Transaction DB to indicate it's failed tx, by reading Tx Receipt.
