### ISSUE TITLE
Please reference original block explorer

### ISSUE THREAD

**Issue by elaineo** [Musicoin/orbiter#22]
Hi. I notice you guys ripped off the ethereum classic block explorer.  Please reference the original repo. Thanks.

http://github.com/ethereumproject/explorer

**Comment by immartian** [comment]
yes, linked, guess you were touted by this guy:
![image](https://cloud.githubusercontent.com/assets/81030/24841818/7b7e6f58-1dbf-11e7-9394-6715fc0fae3f.png)

thanks again for the initial work, we debugged a lot. Why it is not continued any more?

**Comment by elaineo** [comment]
Yes, thank you for adding the link. The Ethereum Classic block explorer is still under active development, which you would know if you had forked the repository instead of cloning the code into your own. (See: https://github.com/ethereumproject/explorer/commits/master)

Also -- I don't know you, I have never spoken to you, and I have no idea what Musicoin is. I don't know why you are telling people that we "had very good comm" or whatever. Please don't do that.

**Comment by immartian** [comment]
check the tweets above. And also the github issues in your repo.  We don't know you too, but there were communications with respect to your early works. Whether you think it's good or not now. 

Please keep your good job with ETC, best lucks.
