### ISSUE TITLE
Only the latest one transaction is shown when selecting 'All' transactions

### ISSUE THREAD

**Issue by frankurcrazy** [Musicoin/orbiter#26]
By selecting 'All' transactions, I can only get one latest transaction.
![image](https://user-images.githubusercontent.com/8373801/27102296-4796a450-50b7-11e7-8410-4db6ecb8bca0.png)

**Comment by frankurcrazy** [comment]
https://github.com/Musicoin/orbiter/blob/40e5a83136b5ebf96e47c5e3be550edc373abc0e/routes/index.js#L73
Maybe it has something to do with the **limit** being -1 when selecting 'All', if that's true, then same issue also exist for other similar functions.

**Comment by immartian** [comment]
I'm looking into that and try to fix it in a shot. :)

**Comment by immartian** [comment]
I have changed limit=0 matching "all", however, it seems very much a grilling to server, and could be a disaster if there are thousands. So I have removed the "all" option totally.  :)
