### ISSUE TITLE
Domain suddenly redirected to https

### ISSUE THREAD

**Issue by immartian** [Musicoin/orbiter#27]
Without any signals, the orbiter site at http://orbiter.musicoin.org was suddenly redirected from browser(FF, Chrome), and can't resolve. 

We didn't put SSL before, so should add it to the service, but the reason is really not perceivable as it worked all time along.

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/orbiter/commit/2957a80e0175029df2d8d27888f7bb343d677fbe
