### ISSUE TITLE
Orbiter sync slower than before

### ISSUE THREAD

**Issue by immartian** [Musicoin/orbiter#33]
The backend catch.js seems much slower these days to sync up the DB once there are more transactions happened on chain. So the frontend seems vastly dragged.  We can reduce the interval between writing each record, but probably it can cause DB panic we can't predict, will try to experiment and improve. 

![image](https://user-images.githubusercontent.com/81030/29748892-88f85846-8b52-11e7-9b11-96f377e47a05.png)

**Comment by douglashipocreme** [comment]
if need .. i can admin and run orbiter on my servers ... let me know .. i am owner of some pools and i want contribute more with musicoin

**Comment by immartian** [comment]
Thanks, maybe we need a backup service. I will share some details here later.

**Comment by brunohass** [comment]
@immartian  as we talked earlier on Slack, I'm done installing Orbiter (https://orbiter.reidocoin.com.br/).
I guess it will take up ages to sync it all. catch.js is running for some time now (+3h), and it's barely on block 2100.
Feel free to contact me if you need testing on a modified version of catch.js.

Cheers!

**Comment by immartian** [comment]
It's seems quite abnormal for the speed of syncing. Are you sure you are running only one catch.js instance.

**Comment by immartian** [comment]
This time it stops at 1062386 for long time and lagged 14 hours.  Obviously Parity runs into panic and returns nothing to node modules. 
```
root@orbiter7762959-1:~# tail /root/.forever/hfzx.log -n 25
error: Script restart attempt #1
No config file found. Using default configuration (will download all blocks starting from latest)
Using configuration:
{ gethPort: 8545,
  output: '.',
  blocks: [ { start: 0, end: 'latest' } ] }
/musicoin/orbiter/node_modules/web3/lib/web3/httpprovider.js:83
        throw errors.InvalidResponse(request.responseText);                
        ^
Error: Invalid JSON RPC response: undefined
    at Object.module.exports.InvalidResponse (/musicoin/orbiter/node_modules/web3/lib/web3/errors.js:35:16)
    at HttpProvider.send (/musicoin/orbiter/node_modules/web3/lib/web3/httpprovider.js:83:22)
    at RequestManager.send (/musicoin/orbiter/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as blockNumber] (/musicoin/orbiter/node_modules/web3/lib/web3/property.js:107:62)
    at patchBlocks (/musicoin/orbiter/tools/catch.js:307:29)
    at Object.<anonymous> (/musicoin/orbiter/tools/catch.js:371:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
error: Forever detected script exited with code: 1
root@orbiter7762959-1:~# ps aux|grep parity
root     12537 28.6  4.1 1673168 639444 ?      Sl   Sep15   4:39 parity --chain mc.json --tracing on```

**Comment by 5chdn** [comment]
^ is that parity or rmc?

**Comment by immartian** [comment]
Found several overlapped nodejs processes twisted, resolved by killing redundant ones.
