### ISSUE TITLE
$ parity --chain mc.json Could not load specification file at mc.json: Permission denied (os error 13)

### ISSUE THREAD

**Issue by jjziets** [Musicoin/orbiter#34]
So as a noob to ubuntu I whish there was some guide as I am stuck  
on ubuntu 16.04 using parity 
installed parity...

$wget https://raw.githubusercontent.com/Musicoin/orbiter/master/mc.json
$ parity --chain mc.json
Could not load specification file at mc.json: Permission denied (os error 13)

~/work/parity$ ls -lsha mc.json
4.0K -rw-rw-r-- 1  2.7K Sep 20 12:58 mc.json

**Comment by jjziets** [comment]
I also have tried the following.

sudo chmod 775 mc.json
cryptolabs@ETHNode:~/work/parity$ parity --chain mc.json
Could not load specification file at mc.json: Permission denied (os error 13)

sudo chown 777 mc.json
cryptolabs@ETHNode:~/work/parity$ parity --chain mc.json
Could not load specification file at mc.json: Permission denied (os error 13)

**Comment by immartian** [comment]
You tried the new RMC and rmc.json linkded in readme ?

**Comment by jjziets** [comment]
I was using 1.8, Now on 1.7.3 and works fine.  will try the rmc.json but 0/mc.json works so far
