### ISSUE TITLE
Orbiter stuck on 1199999?

### ISSUE THREAD

**Issue by 5chdn** [Musicoin/orbiter#36]
- https://orbiter.musicoin.org/home

I'm curious why, if it does not support the fork, shouldn't it be stuck on 1200000?

Is it running an old RMC version? Make sure fork num is 1200001!

Did you consider running Parity nightly as backend?

**Comment by immartian** [comment]
re-syncing to check what's the reason.

**Comment by immartian** [comment]
there could be some peers not good, so stuck there times but finally passed
![image](https://user-images.githubusercontent.com/81030/31412399-884b94d6-ae47-11e7-8660-656781b4696c.png)

**Comment by 5chdn** [comment]
Looks good now. Yes my peers also dropped significantly at the moment of the fork. Now only GMC2.0 and Parity1.8 nodes are connected, but that's expected.
