### ISSUE TITLE
orbiter.musicoin.org shows only old blocks

### ISSUE THREAD

**Issue by Angel996** [Musicoin/orbiter#41]
Hi.

All blocks shown on orbiter are at least 8 hours old, URL links to view them are not working (https://orbiter.musicoin.org/block/1228958) err 404.

**Comment by immartian** [comment]
Ya, we are resyncing the chain and DB for presentation.  Play stay tuned for a while.

**Comment by Varunram** [comment]
Closing this since it has been resolved since.
