### ISSUE TITLE
MUSIC not being deposited

### ISSUE THREAD

**Issue by shadowjuan** [Musicoin/orbiter#46]
Hi all, yesterday I made a deposit to Cryptopia of 28.xxx MUSICs and it has not yet arrived.

I have tested the wallet address and the explorer keeps loading some info forever. And have no more clues.

Info of tx is this:

    Address: 0x33919fb747f70f51b188ec17e0c10809d5a63bf0
    TxId: 0xafcc2ad2b971f4ea887e3223be16a93f812ca71271afc9bbab07badd418440db

Thanks!

**Comment by Varunram** [comment]
Cryptopia is currently off-line and they aren't responding to our support emails. Please contact Cryptopia support so that they can help you out. We are working with other exchanges to get Musicoin listed, so that choice isn't limited.
