### ISSUE TITLE
music not deposit on criptopia

### ISSUE THREAD

**Issue by giangict** [Musicoin/orbiter#47]
Hi all, 
 I made a deposit to Cryptopia of  MUSICs and it has not yet arrived.
I have tested the wallet address and the explorer keeps loading some info forever. And have no more clues.
Info of tx is this:

Address: 0xbb7b4f230220be7bd21ed2026bee864c8415f140
TxId: 0x42ce85d6f1f2839f0fd16303ffe1034793d71f2319dcc5358f82a01205d14815

**Comment by Varunram** [comment]
Cryptopia is currently off-line and they aren't responding to our support emails. Please contact Cryptopia support so that they can help you out.
