### ISSUE TITLE
Musicoin Not being deposited. Problem is there is no connection. 

### ISSUE THREAD

**Issue by v84shubh2abet** [Musicoin/orbiter#49]
What's happening? Could please anyone from the team help? 
There is 0 connection shown in the below link. 
https://www.cryptopia.co.nz/CoinInfo/?coin=MUSIC&view=settings

So is there someone working on it? What to do? 
Help would be appreciated. 
My transaction hash: 
0x62a061e91238fa19dcdba95eb102e119cf1874dd98c62b98c285109c99f1ba9c

**Comment by Varunram** [comment]
Cryptopia is currently off-line and they aren't responding to our support emails. Please contact Cryptopia support so that they can help you out. We are working with other exchanges to get Musicoin listed, so that choice isn't limited.
